# Generated by Django 4.2.20 on 2025-03-26 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cooking', '0002_recipe_buyers_recipe_choosers_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favourites',
            name='FavouritesUK',
        ),
        migrations.RemoveConstraint(
            model_name='shoppinglist',
            name='ShoppingListUK',
        ),
        migrations.AlterField(
            model_name='favourites',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cooking.recipe', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='favourites',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
