# Generated by Django 4.2.20 on 2025-03-26 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0003_remove_favourites_favouritesuk_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='picture',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='description',
            new_name='text',
        ),
    ]
