# Generated by Django 4.2.20 on 2025-03-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0004_rename_picture_recipe_image_rename_title_recipe_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipe',
            name='AuthorTitle',
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(fields=('author', 'name'), name='RecipeUK'),
        ),
    ]
