# Generated by Django 4.2.20 on 2025-03-27 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0005_remove_recipe_authortitle_recipe_recipeuk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='unit',
            new_name='measurement_unit',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='сomposition',
            old_name='quantity',
            new_name='amount',
        ),
    ]
