# Generated by Django 4.2.20 on 2025-03-27 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0007_alter_сomposition_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='сomposition',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='go_here', to='cooking.recipe', verbose_name='Рецепт'),
        ),
    ]
