# Generated by Django 4.2.20 on 2025-03-29 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0009_alter_сomposition_recipe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Сomposition',
            new_name='Composition',
        ),
    ]
