# Generated by Django 4.2.20 on 2025-04-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0011_alter_follow_author_alter_follow_follower'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.URLField(unique=True, verbose_name='Исходная ссылка на рецепт ')),
                ('abridged', models.CharField(max_length=50, unique=True, verbose_name='Код рецепта')),
            ],
            options={
                'verbose_name': 'перенаправление ссылки',
                'verbose_name_plural': 'Перенаправление ссылок',
            },
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='pictures/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='text',
            field=models.TextField(verbose_name='Текстовое описание'),
        ),
    ]
