# Generated by Django 4.2.20 on 2025-04-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0012_shortlink_alter_recipe_image_alter_recipe_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата-время создания записи'),
        ),
    ]
