# Generated by Django 4.2.20 on 2025-04-15 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0014_alter_recipe_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-created'], 'verbose_name': 'рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
    ]
