# Generated by Django 4.2.20 on 2025-04-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatars/default_avatar.png', upload_to='avatars/', verbose_name='avatar'),
        ),
    ]
